<?php

$services = [
  'Residential Cleaning' => [
    ['Standard House Cleaning', '$100 – $220'],
    ['Deep Cleaning', '$150 – $350'],
    ['Move-In / Move-Out Cleaning', '$180 – $400'],
    ['Apartment Cleaning – 1 BR', '$80 – $150'],
    ['Apartment Cleaning – 2–3 BR', '$120 – $250'],
    ['Kitchen Deep Cleaning', '$70 – $180'],
    ['Bathroom Deep Cleaning', '$60 – $140'],
    ['Bedroom Cleaning (single room)', '$45 – $110'],
    ['Living Room Cleaning', '$55 – $120'],
    ['Fridge or Oven Interior (each)', '$20 – $60'],
    ['Baseboard Cleaning', '$40 – $110'],
    ['Window Cleaning (per window, in/out)', '$5 – $12'],
    ['Carpet Cleaning (per room)', '$35 – $80'],
    ['Upholstery Cleaning (sofa)', '$60 – $160'],
    ['Mattress Cleaning', '$80 – $160'],
  ],
  'Commercial & Office' => [
    ['Office Cleaning (recurring janitorial)', '$0.11 – $0.20 / sq ft'],
    ['Small Office Visit (< 1,000 sq ft)', '$120 – $300'],
    ['Medium Office Visit (1,000–2,000 sq ft)', '$200 – $400'],
    ['Commercial Carpet Shampoo', '$0.20 – $0.45 / sq ft'],
    ['Floor Stripping & Waxing', '$0.25 – $0.50 / sq ft'],
    ['Restroom Sanitation Service', '$60 – $150'],
    ['Breakroom Cleaning & Supply Refill', '$70 – $180'],
    ['High Dusting / Vent Cleaning', '$80 – $250'],
    ['Trash Removal & Recycling', '$50 – $200'],
    ['Exterior Window Cleaning (commercial)', '$4 – $8 / window'],
  ],
  'Post-Construction & Specialized' => [
    ['Post-Construction Cleanup', '$0.50 – $1.00 / sq ft'],
    ['Post-Renovation Cleaning', '$0.40 – $0.85 / sq ft'],
    ['Pressure Washing (driveways, decks)', '$120 – $400'],
    ['Graffiti Removal', '$150 – $500'],
    ['Exterior Building Washing', '$200 – $600'],
    ['Industrial Floor Cleaning', '$0.30 – $0.70 / sq ft'],
    ['Warehouse Cleaning', '$0.10 – $0.35 / sq ft'],
    ['Equipment & Machine Cleaning (light)', '$100 – $400 / unit'],
  ],
  'Disinfection & Sanitation' => [
    ['Full Disinfection Service', '$150 – $400'],
    ['Electrostatic Spraying', '$0.20 – $0.45 / sq ft'],
    ['Odor Removal Treatment', '$120 – $300'],
    ['Air Vent & Duct Cleaning', '$300 – $600'],
    ['Mold Prevention & Surface Treatment', '$150 – $450'],
  ],
  'Exterior & Maintenance' => [
    ['Gutter Cleaning', '$100 – $250'],
    ['Driveway Cleaning', '$90 – $220'],
    ['Patio & Deck Cleaning', '$110 – $300'],
    ['Roof Soft Wash', '$200 – $650'],
    ['Solar Panel Cleaning', '$90 – $230'],
    ['Window Screen Replacement', '$20 – $45 each'],
  ],
  'Add-Ons & Upgrades' => [
    ['Organization (closets, garage)', '$80 – $250'],
    ['Laundry & Linen Service', '$30 – $90'],
    ['Pet Hair Removal', '$25 – $60'],
    ['Eco-Friendly Cleaning Upgrade', '+10% of base'],
    ['Emergency Cleaning (same-day)', 'Base + ~25%'],
  ],
];

